/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol;

type ArrayOf<T> = Array<T & {
  _key: string;
}>;

// Source: schema.json
export type Subscriber = {
  _id: string;
  _type: "subscriber";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  email?: string;
  subscribedAt?: string;
  source?: string;
  exportedAt?: string;
};

export type Enquiry = {
  _id: string;
  _type: "enquiry";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  kind?: "sponsor" | "performer" | "table" | "member" | "volunteer" | "enrol" | "vendor" | "contact";
  sponsor?: EnquirySponsorFields;
  performer?: EnquiryPerformerFields;
  table?: EnquiryTableFields;
  member?: EnquiryMemberFields;
  volunteer?: EnquiryVolunteerFields;
  enrol?: EnquiryEnrolFields;
  vendor?: EnquiryVendorFields;
  contact?: EnquiryContactFields;
  submittedAt?: string;
  source?: string;
  notifiedAt?: string;
  notifyError?: string;
  handled?: boolean;
  notes?: string;
};

export type EnquiryContactFields = {
  _type: "enquiryContactFields";
  name?: string;
  mail?: string;
  subject?: string;
  message?: string;
};

export type EnquiryVendorFields = {
  _type: "enquiryVendorFields";
  biz?: string;
  who?: string;
  mail?: string;
  phone?: string;
  cat?: "Food, cooked on site" | "Packaged food and drink" | "Cloth and clothing" | "Craft and art" | "Books and media" | "Something else";
  size?: "Standard booth" | "Double booth" | "Food truck";
  power?: "No" | "Yes";
  permit?: string;
  social?: string;
};

export type EnquiryEnrolFields = {
  _type: "enquiryEnrolFields";
  learner?: string;
  age?: string;
  level?: "Not sure, let the teacher place them" | "None yet" | "Understands but does not speak" | "Speaks a little" | "Speaks well, wants to read and write";
  when?: "Weekday evenings" | "Weekend mornings" | "Weekend afternoons" | "Flexible, let the teacher propose";
  guardian?: string;
  mail?: string;
  phone?: string;
  notes?: string;
};

export type EnquiryVolunteerFields = {
  _type: "enquiryVolunteerFields";
  name?: string;
  mail?: string;
  phone?: string;
  age?: "Adult" | "Under 18";
  avail?: "Event days" | "Weekends" | "Weekdays" | "Any of these";
  where?: string;
  skills?: string;
  notes?: string;
};

export type EnquiryMemberFields = {
  _type: "enquiryMemberFields";
  name?: string;
  mail?: string;
  phone?: string;
  city?: string;
  household?: "Individual" | "Household";
  hta?: string;
  heard?: string;
  why?: string;
};

export type EnquiryTableFields = {
  _type: "enquiryTableFields";
  name?: string;
  org?: string;
  mail?: string;
  phone?: string;
  count?: "One table" | "Two tables" | "Three or more";
  guests?: string;
};

export type EnquiryPerformerFields = {
  _type: "enquiryPerformerFields";
  group?: string;
  who?: string;
  mail?: string;
  what?: string;
  link?: string;
  size?: string;
};

export type EnquirySponsorFields = {
  _type: "enquirySponsorFields";
  org?: string;
  who?: string;
  mail?: string;
  interest?: "Odunde Festival" | "End-of-Year Gala" | "Both events" | "Yoruba Cultural Collective" | "Programs" | "General, tell me more";
};

export type LintReport = {
  _id: string;
  _type: "lintReport";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  documentId?: string;
  documentType?: string;
  title?: string;
  checkedRev?: string;
  checkedAt?: string;
  findings?: Array<{
    path?: string;
    kind?: "em-dash" | "marks";
    message?: string;
    excerpt?: string;
    _type: "lintFinding";
    _key: string;
  }>;
};

export type SanityFileAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.fileAsset";
};

export type GovernanceDoc = {
  _id: string;
  _type: "governanceDoc";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  kind?: "form990" | "annualReport" | "audit";
  year?: string;
  file?: {
    asset?: SanityFileAssetReference;
    media?: unknown;
    _type: "file";
  };
  note?: string;
};

export type GivingLevel = {
  _id: string;
  _type: "givingLevel";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  amount?: string;
  what?: string;
  frequency?: "once" | "monthly";
  source?: string;
  order?: number;
};

export type HometownAssociation = {
  _id: string;
  _type: "hometownAssociation";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  url?: string;
};

export type Door = {
  _id: string;
  _type: "door";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  key?: "member" | "volunteer" | "partner" | "give";
  title?: string;
  blurb?: string;
  bullets?: Array<string>;
  action?: Cta;
  image?: OyImage;
  order?: number;
};

export type SanityImageAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
};

export type PhotographerReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "photographer";
};

export type OyImage = {
  _type: "oyImage";
  asset?: SanityImageAssetReference;
  media?: unknown;
  hotspot?: SanityImageHotspot;
  crop?: SanityImageCrop;
  alt?: string;
  caption?: string;
  credit?: PhotographerReference;
  creditNote?: string;
  creditConfirmed?: boolean;
};

export type Cta = {
  _type: "cta";
  label?: string;
  kind?: "enquiry" | "give" | "url" | "anchor";
  enquiryKind?: "sponsor" | "performer" | "table" | "member" | "volunteer" | "enrol" | "vendor" | "contact";
  href?: string;
  newTab?: boolean;
};

export type Stat = {
  _id: string;
  _type: "stat";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  value?: string;
  label?: string;
  source?: string;
  asOf?: string;
};

export type ProgramReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "program";
};

export type Outcome = {
  _id: string;
  _type: "outcome";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  program?: ProgramReference;
  title?: string;
  figure?: SourcedFigure;
  plainStatement?: string;
  year?: string;
  order?: number;
};

export type SourcedFigure = {
  _type: "sourcedFigure";
  value?: string;
  label?: string;
  source?: string;
  asOf?: string;
};

export type Partner = {
  _id: string;
  _type: "partner";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  logo?: OyImage;
  url?: string;
  kind?: "funder" | "partner" | "sponsor";
  scope?: Array<string>;
};

export type EventReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "event";
};

export type PersonReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "person";
};

export type NewsPost = {
  _id: string;
  _type: "newsPost";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  date?: string;
  kicker?: Bilingual;
  summary?: string;
  body?: BlockContent;
  image?: OyImage;
  tags?: ArrayOf<ProgramReference | EventReference>;
  author?: PersonReference;
};

export type BlockContent = Array<{
  children?: Array<{
    marks?: Array<string>;
    text?: string;
    _type: "span";
    _key: string;
  }>;
  style?: "normal" | "h3" | "blockquote";
  listItem?: never;
  markDefs?: Array<{
    href?: string;
    _type: "link";
    _key: string;
  }>;
  level?: number;
  _type: "block";
  _key: string;
} | {
  _key: string;
} & PullQuote>;

export type Bilingual = {
  _type: "bilingual";
  yo?: string;
  en?: string;
};

export type Slug = {
  _type: "slug";
  current?: string;
  source?: string;
};

export type TimelineEntry = {
  _id: string;
  _type: "timelineEntry";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  year?: string;
  title?: string;
  blurb?: string;
  image?: OyImage;
  order?: number;
};

export type Initiative = {
  _id: string;
  _type: "initiative";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  memberLed?: boolean;
  status?: "planned" | "piloting" | "running";
  statusLine?: string;
  blurb?: string;
  image?: OyImage;
  serves?: string;
  since?: string;
  next?: string;
  proceedsReturn?: boolean;
  order?: number;
};

export type Honoree = {
  _id: string;
  _type: "honoree";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  event?: EventReference;
  name?: string;
  award?: string;
  blurb?: string;
  image?: OyImage;
};

export type SponsorLevel = {
  _id: string;
  _type: "sponsorLevel";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  scope?: "odunde" | "gala" | "org";
  event?: EventReference;
  name?: string;
  amount?: string;
  recognition?: Array<string>;
  order?: number;
};

export type TicketTier = {
  _id: string;
  _type: "ticketTier";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  event?: EventReference;
  name?: string;
  price?: string;
  includes?: Array<string>;
  variant?: "buyNow" | "enquiry";
  featured?: boolean;
  order?: number;
};

export type NewsPage = {
  _id: string;
  _type: "newsPage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  header?: PageHeader;
  layout?: {
    order?: "events-led" | "feed-led";
    filtersShown?: "shown" | "hidden";
  };
  seo?: Seo;
};

export type Seo = {
  _type: "seo";
  title?: string;
  description?: string;
  ogImage?: OyImage;
};

export type PageHeader = {
  _type: "pageHeader";
  kicker?: Bilingual;
  title?: string;
  line?: string;
  image?: OyImage;
};

export type GalleryPage = {
  _id: string;
  _type: "galleryPage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  header?: PageHeader;
  intro?: string;
  creditsAndConsent?: BlockContent;
  primaryAction?: Cta;
  secondaryActions?: Array<{
    _key: string;
  } & Cta>;
  layout?: {
    open?: "viewer" | "grid";
    captions?: "always" | "hover";
    state?: "built" | "soon";
  };
  seo?: Seo;
};

export type DoorReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "door";
};

export type GivingLevelReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "givingLevel";
};

export type DonatePage = {
  _id: string;
  _type: "donatePage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  header?: PageHeader;
  giveNow?: {
    title?: string;
    blurb?: string;
  };
  largerScale?: {
    title?: string;
    blurb?: string;
    doors?: Array<{
      _key: string;
    } & DoorReference>;
  };
  whatYourGiftDoes?: Array<{
    _key: string;
  } & GivingLevelReference>;
  otherWays?: Array<{
    title?: string;
    blurb?: string;
    _type: "otherWay";
    _key: string;
  }>;
  taxLine?: string;
  primaryAction?: Cta;
  secondaryActions?: Array<{
    _key: string;
  } & Cta>;
  layout?: {
    impact?: "shown" | "hidden";
  };
  seo?: Seo;
};

export type TimelineEntryReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "timelineEntry";
};

export type StoryPage = {
  _id: string;
  _type: "storyPage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  header?: PageHeader;
  founding?: BlockContent;
  timeline?: Array<{
    _key: string;
  } & TimelineEntryReference>;
  boardIntro?: string;
  staffIntro?: string;
  reachUs?: {
    title?: string;
    blurb?: string;
  };
  primaryAction?: Cta;
  secondaryActions?: Array<{
    _key: string;
  } & Cta>;
  layout?: {
    timeline?: "hidden" | "shown";
    bios?: "short" | "full";
    portraits?: "shown" | "hidden";
  };
  seo?: Seo;
};

export type StatReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "stat";
};

export type OutcomeReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "outcome";
};

export type TestimonialReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "testimonial";
};

export type ImpactPage = {
  _id: string;
  _type: "impactPage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  header?: PageHeader;
  stats?: Array<{
    _key: string;
  } & StatReference>;
  howWeWork?: BlockContent;
  outcomes?: Array<{
    _key: string;
  } & OutcomeReference>;
  civicInfra?: BlockContent;
  voices?: Array<{
    _key: string;
  } & TestimonialReference>;
  photos?: Array<{
    _key: string;
  } & OyImage>;
  fundersIntro?: string;
  nextYear?: {
    title?: string;
    blurb?: string;
  };
  primaryAction?: Cta;
  secondaryActions?: Array<{
    _key: string;
  } & Cta>;
  layout?: {
    stats?: "four" | "six";
    outcomes?: "cards" | "rows";
    sources?: "shown" | "hidden";
    funders?: "shown" | "hidden";
  };
  seo?: Seo;
};

export type GetInvolvedPage = {
  _id: string;
  _type: "getInvolvedPage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  header?: PageHeader;
  doors?: Array<{
    _key: string;
  } & DoorReference>;
  hometownAssociations?: {
    title?: string;
    prose?: BlockContent;
  };
  fallback?: {
    title?: string;
    blurb?: string;
  };
  primaryAction?: Cta;
  secondaryActions?: Array<{
    _key: string;
  } & Cta>;
  layout?: {
    doors?: "cards" | "rows";
    hta?: "shown" | "hidden";
  };
  seo?: Seo;
};

export type InitiativeReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "initiative";
};

export type CollectivePage = {
  _id: string;
  _type: "collectivePage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  header?: PageHeader;
  argument?: BlockContent;
  initiatives?: Array<{
    _key: string;
  } & InitiativeReference>;
  voice?: TestimonialReference;
  keepsOwnList?: boolean;
  primaryAction?: Cta;
  secondaryActions?: Array<{
    _key: string;
  } & Cta>;
  layout?: {
    initiatives?: "side" | "stacked";
    green?: "signal" | "strong";
    status?: "shown" | "hidden";
    events?: "shown" | "hidden";
  };
  seo?: Seo;
};

export type Testimonial = {
  _id: string;
  _type: "testimonial";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  quote?: string;
  name?: string;
  relation?: string;
  permissionToName?: boolean;
  context?: "lessons" | "festival" | "collective" | "general";
};

export type LessonsPage = {
  _id: string;
  _type: "lessonsPage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  header?: PageHeader;
  glance?: Array<{
    _key: string;
  } & Fact>;
  teacher?: PersonReference;
  teacherIntro?: string;
  levels?: Array<{
    name?: string;
    blurb?: string;
    _type: "level";
    _key: string;
  }>;
  oneLesson?: Array<{
    step?: string;
    title?: string;
    detail?: string;
    _type: "lessonStep";
    _key: string;
  }>;
  faq?: Array<{
    _key: string;
  } & FaqItem>;
  voices?: Array<{
    _key: string;
  } & TestimonialReference>;
  primaryAction?: Cta;
  secondaryActions?: Array<{
    _key: string;
  } & Cta>;
  layout?: {
    lesson?: "shown" | "hidden";
    portraits?: "shown" | "hidden";
    faq?: "closed" | "open";
  };
  seo?: Seo;
};

export type Person = {
  _id: string;
  _type: "person";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  role?: string;
  group?: "board" | "staff" | "volunteer" | "teacher";
  portrait?: OyImage;
  bioShort?: string;
  bioFull?: BlockContent;
  order?: number;
};

export type ProgramsPage = {
  _id: string;
  _type: "programsPage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  header?: PageHeader;
  intro?: string;
  kidsStem?: {
    title?: string;
    ages?: string;
    blurb?: string;
    image?: OyImage;
    subprograms?: Array<{
      name?: string;
      ages?: string;
      blurb?: string;
      detail?: string;
      action?: Cta;
      _type: "subprogram";
      _key: string;
    }>;
  };
  culturalExchange?: {
    title?: string;
    blurb?: string;
    image?: OyImage;
    cadence?: string;
    eligibility?: string;
    howToJoin?: string;
  };
  yearStrip?: Array<{
    when?: string;
    program?: ProgramReference;
    event?: EventReference;
    note?: string;
    _type: "yearStripRow";
    _key: string;
  }>;
  primaryAction?: Cta;
  secondaryActions?: Array<{
    _key: string;
  } & Cta>;
  layout?: {
    cards?: "four" | "three" | "pairs";
    inline?: "expanded" | "collapsed";
    yearstrip?: "shown" | "hidden";
  };
  seo?: Seo;
};

export type Program = {
  _id: string;
  _type: "program";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  slug?: Slug;
  kicker?: Bilingual;
  blurb?: string;
  image?: OyImage;
  cadence?: string;
  ages?: string;
  page?: "lessons" | "collective";
  order?: number;
};

export type GalaPage = {
  _id: string;
  _type: "galaPage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  header?: PageHeader;
  extraFacts?: Array<{
    _key: string;
  } & Fact>;
  eveningIntro?: string;
  tiersIntro?: string;
  sponsorIntro?: string;
  honoreesIntro?: string;
  pastIntro?: string;
  takePartOrder?: Array<string>;
  primaryAction?: Cta;
  secondaryActions?: Array<{
    _key: string;
  } & Cta>;
  layout?: {
    treatment?: "formal" | "warm";
    tiers?: "columns" | "rows";
    emphasis?: "seats" | "tables";
    awards?: "shown" | "hidden";
    schedule?: "shown" | "hidden";
    past?: "shown" | "hidden";
    labels?: "column" | "none" | "kicker";
  };
  seo?: Seo;
};

export type FestivalPage = {
  _id: string;
  _type: "festivalPage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  header?: PageHeader;
  extraFacts?: Array<{
    _key: string;
  } & Fact>;
  whatItIs?: BlockContent;
  zonesIntro?: string;
  planYourVisit?: Array<{
    _key: string;
  } & Fact>;
  takePartOrder?: Array<string>;
  pastYearsIntro?: string;
  partnersIntro?: string;
  primaryAction?: Cta;
  secondaryActions?: Array<{
    _key: string;
  } & Cta>;
  layout?: {
    phead?: "photo" | "slim";
    zones?: "mosaic" | "five" | "grid" | "list";
    schedule?: "shown" | "collapsed" | "hidden";
    takepart?: "vendor" | "sponsor";
    labels?: "column" | "none" | "kicker";
  };
  seo?: Seo;
};

export type Homepage = {
  _id: string;
  _type: "homepage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  hero?: {
    kicker?: Bilingual;
    title?: string;
    sub?: string;
    image?: OyImage;
    primaryAction?: Cta;
    secondaryActions?: Array<{
      _key: string;
    } & Cta>;
  };
  leadEvent?: EventReference;
  stats?: Array<{
    _key: string;
  } & StatReference>;
  programsIntro?: string;
  voices?: Array<{
    _key: string;
  } & TestimonialReference>;
  newsIntro?: string;
  yearInLife?: Array<{
    _key: string;
  } & OyImage>;
  raiseYourHand?: {
    title?: string;
    blurb?: string;
    doors?: Array<{
      _key: string;
    } & DoorReference>;
  };
  layout?: {
    season?: "auto" | "gala" | "odunde";
    highlight?: "festival" | "school" | "collective";
    gallery?: "7" | "5" | "3";
    involved?: "doors" | "rows";
    newsletter?: "footer" | "band";
    pattern?: "rich" | "subtle";
    motion?: "on" | "off";
  };
  seo?: Seo;
};

export type AlbumReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "album";
};

export type Event = {
  _id: string;
  _type: "event";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  kind?: "festival" | "gala" | "collective" | "other";
  title?: string;
  edition?: number;
  start?: string;
  end?: string;
  doors?: string;
  venue?: {
    name?: string;
    address?: string;
    line?: string;
  };
  cost?: string;
  dress?: string;
  heroImage?: OyImage;
  summary?: string;
  ticketsUrl?: string;
  album?: AlbumReference;
  attendance?: SourcedFigure;
  schedule?: Array<{
    _key: string;
  } & ScheduleItem>;
  vendorTerms?: {
    fees?: string;
    closeDate?: string;
    decisionDate?: string;
    permitNote?: string;
  };
};

export type Album = {
  _id: string;
  _type: "album";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  date?: string;
  event?: EventReference;
  cover?: OyImage;
  photos?: Array<{
    _key: string;
  } & OyImage>;
  credit?: PhotographerReference;
  creditConfirmed?: boolean;
  consentNote?: string;
};

export type SiteSettings = {
  _id: string;
  _type: "siteSettings";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  orgName?: string;
  wordmarkLine2?: string;
  logo?: OyImage;
  ein?: string;
  address?: string;
  phone?: string;
  generalEmail?: string;
  contacts?: Array<{
    _key: string;
  } & ContactRole>;
  socials?: Array<{
    network?: "instagram" | "facebook" | "linkedin" | "youtube";
    url?: string;
    _type: "social";
    _key: string;
  }>;
  footerBlurb?: string;
  newsletterTitle?: string;
  newsletterBlurb?: string;
  zeffyEmbedUrl?: string;
  eventbriteUrl?: string;
  analyticsEnabled?: boolean;
  theme?: "adire" | "calm" | "festival";
};

export type PullQuote = {
  _type: "pullQuote";
  quote?: string;
  name?: string;
  relation?: string;
};

export type ContactRole = {
  _type: "contactRole";
  role?: "membership" | "volunteers" | "partnerships" | "vendors" | "performers" | "tables" | "teacher" | "general";
  name?: string;
  email?: string;
  phone?: string;
  responds?: string;
};

export type FaqItem = {
  _type: "faqItem";
  question?: string;
  answer?: BlockContent;
};

export type ZoneReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "zone";
};

export type ScheduleItem = {
  _type: "scheduleItem";
  time?: string;
  day?: string;
  title?: string;
  titleYo?: string;
  detail?: string;
  zone?: ZoneReference;
};

export type Zone = {
  _id: string;
  _type: "zone";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: Bilingual;
  line?: string;
  image?: OyImage;
  order?: number;
  active?: boolean;
};

export type Fact = {
  _type: "fact";
  label?: string;
  value?: string;
  note?: string;
};

export type Photographer = {
  _id: string;
  _type: "photographer";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  url?: string;
  defaultCredit?: string;
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top?: number;
  bottom?: number;
  left?: number;
  right?: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x?: number;
  y?: number;
  height?: number;
  width?: number;
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height?: number;
  width?: number;
  aspectRatio?: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  thumbHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type AllSanitySchemaTypes = Subscriber | Enquiry | EnquiryContactFields | EnquiryVendorFields | EnquiryEnrolFields | EnquiryVolunteerFields | EnquiryMemberFields | EnquiryTableFields | EnquiryPerformerFields | EnquirySponsorFields | LintReport | SanityFileAssetReference | GovernanceDoc | GivingLevel | HometownAssociation | Door | SanityImageAssetReference | PhotographerReference | OyImage | Cta | Stat | ProgramReference | Outcome | SourcedFigure | Partner | EventReference | PersonReference | NewsPost | BlockContent | Bilingual | Slug | TimelineEntry | Initiative | Honoree | SponsorLevel | TicketTier | NewsPage | Seo | PageHeader | GalleryPage | DoorReference | GivingLevelReference | DonatePage | TimelineEntryReference | StoryPage | StatReference | OutcomeReference | TestimonialReference | ImpactPage | GetInvolvedPage | InitiativeReference | CollectivePage | Testimonial | LessonsPage | Person | ProgramsPage | Program | GalaPage | FestivalPage | Homepage | AlbumReference | Event | Album | SiteSettings | PullQuote | ContactRole | FaqItem | ZoneReference | ScheduleItem | Zone | Fact | Photographer | SanityImageCrop | SanityImageHotspot | SanityImagePaletteSwatch | SanityImagePalette | SanityImageDimensions | SanityImageMetadata | SanityFileAsset | SanityAssetSourceData | SanityImageAsset | Geopoint;

