#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.
#
# One deviation from the template: `tput dim` tolerates terminals without that capability
# (konsole, putty, rxvt), which would otherwise abort the script under set -e.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim 2>/dev/null || true); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=7

# Run from anywhere: every path below is relative to the repo root.
cd "$(dirname "${BASH_SOURCE[0]}")/.."

# Astro reads env from the app directory, so values land in apps/web/.env unless the caller
# set ENV_FILE (the library's documented override). Secrets are typed hidden and never echoed.
if [[ "$ENV_FILE" == ".env" ]]; then ENV_FILE="apps/web/.env"; fi
FUNCTIONS_ENV_FILE="packages/content/.env"
SITE_URL_DEFAULT="https://omoyorubaofsocal.org"
LOCAL_URL="http://localhost:4321"

VERCEL_READY=0
if command -v vercel >/dev/null 2>&1 && [[ -f apps/web/.vercel/project.json ]]; then VERCEL_READY=1; fi

# vercel_env KEY VALUE [ENV...] sets KEY on the linked Vercel project for the named
# environments (default: production, preview, development). It removes any existing value
# first, so it works on every CLI version, and refuses to push an empty value.
vercel_env() {
  local key="$1" value="$2"; shift 2
  local envs=("$@"); (( ${#envs[@]} )) || envs=(production preview development)
  if [[ -z "$value" ]]; then
    SKIPPED+=("Vercel env $key: empty locally, left untouched")
    warn "skipped Vercel env $key: no value to push"
    return
  fi
  if (( ! VERCEL_READY )); then
    SKIPPED+=("Vercel env $key (link first: cd apps/web && vercel link, then re-run)")
    return
  fi
  local env
  for env in "${envs[@]}"; do
    (cd apps/web && vercel env rm "$key" "$env" --yes >/dev/null 2>&1) || true
    if printf '%s' "$value" | (cd apps/web && vercel env add "$key" "$env" >/dev/null 2>&1); then
      printf '  %s✓ set%s Vercel %s (%s)\n' "$GREEN" "$RESET" "$key" "$env"
    else
      SKIPPED+=("Vercel env $key ($env): the CLI refused; set it in the dashboard")
      warn "could not set Vercel env $key for $env"
    fi
  done
}

# ensure_secret KEY keeps an existing value from the env file or generates a new one.
ensure_secret() {
  local key="$1" value
  value=$(_existing "$key" || true)
  if [[ -n "$value" ]]; then
    note "$key already set, keeping it"
  else
    value=$(openssl rand -hex 32)
    write_env "$key" "$value"
  fi
  printf -v "$key" '%s' "$value"
}

banner "Omo Yorùbá site: services setup"

# Stage 1
stage "Sanity: project and datasets"
say "Create the content project. The Studio is embedded in the site at /admin."
open_url "https://www.sanity.io/manage"
step "Create a project named 'Omo Yorùbá of Southern California' in your organisation."
step "Add a dataset named 'production' (public) and a second one named 'development'."
step "Under API, add CORS origins: $LOCAL_URL (allow credentials) and $SITE_URL_DEFAULT."
step "Copy the Project ID shown on the project page."
ask PUBLIC_SANITY_PROJECT_ID "Paste the Sanity project ID:"
ask PUBLIC_SANITY_DATASET "Dataset for local work [production]:"
PUBLIC_SANITY_DATASET="${PUBLIC_SANITY_DATASET:-production}"
write_env PUBLIC_SANITY_PROJECT_ID "$PUBLIC_SANITY_PROJECT_ID"
write_env PUBLIC_SANITY_DATASET "$PUBLIC_SANITY_DATASET"
write_env PUBLIC_SITE_URL "$LOCAL_URL"
pause

# Stage 2
stage "Sanity: API tokens and secrets"
say "Two tokens: a Viewer token for reads and drafts, an Editor token the enquiry actions use."
open_url "https://www.sanity.io/manage"
step "Open the project, then API, then Tokens, then Add API token."
step "Name it 'site read', permissions Viewer, copy it."
ask_secret SANITY_API_READ_TOKEN "Paste the Viewer token:"
step "Add a second token named 'enquiries write', permissions Editor, copy it."
ask_secret SANITY_API_WRITE_TOKEN "Paste the Editor token:"
write_env SANITY_API_READ_TOKEN "$SANITY_API_READ_TOKEN"
write_env SANITY_API_WRITE_TOKEN "$SANITY_API_WRITE_TOKEN"
say "The preview secret and the webhook secret are generated here, or kept from a previous run."
ensure_secret SANITY_PREVIEW_SECRET
ensure_secret SANITY_WEBHOOK_SECRET
pause

# Stage 3
stage "Vercel: project, settings and environment variables"
say "The site deploys from apps/web. Linking is interactive and runs the Vercel CLI here."
if command -v vercel >/dev/null 2>&1; then
  if [[ -f apps/web/.vercel/project.json ]]; then
    note "apps/web is already linked to a Vercel project"
  elif confirm "Run 'vercel link' in apps/web now?"; then
    (cd apps/web && vercel link) || warn "vercel link did not finish; run it by hand later"
  fi
  [[ -f apps/web/.vercel/project.json ]] && VERCEL_READY=1
else
  warn "Vercel CLI not found. Install it (npm i -g vercel) or set the variables in the dashboard."
fi
open_url "https://vercel.com/dashboard"
step "Open the project, then Settings, then Build and Deployment."
step "Root Directory: apps/web, with 'Include files outside the root directory' enabled."
step "Framework Preset: Astro. Node.js Version: 22.x (apps/web/package.json also pins it)."
step "Under Domains, add omoyorubaofsocal.org (and www) when you are ready to point DNS."
if (( VERCEL_READY )) && confirm "Push the values from $ENV_FILE to Vercel now? Existing values are replaced."; then
  vercel_env PUBLIC_SANITY_PROJECT_ID "$PUBLIC_SANITY_PROJECT_ID"
  vercel_env PUBLIC_SANITY_DATASET "production" production preview
  vercel_env PUBLIC_SANITY_DATASET "$PUBLIC_SANITY_DATASET" development
  vercel_env PUBLIC_SITE_URL "$SITE_URL_DEFAULT" production preview
  vercel_env PUBLIC_SITE_URL "$LOCAL_URL" development
  vercel_env SANITY_API_READ_TOKEN "$SANITY_API_READ_TOKEN"
  vercel_env SANITY_API_WRITE_TOKEN "$SANITY_API_WRITE_TOKEN"
  vercel_env SANITY_PREVIEW_SECRET "$SANITY_PREVIEW_SECRET"
  vercel_env SANITY_WEBHOOK_SECRET "$SANITY_WEBHOOK_SECRET"
else
  SKIPPED+=("Vercel environment variables: push them later by re-running stage 3, or add them in the dashboard")
fi
note "PUBLIC_ZEFFY_EMBED_URL and PUBLIC_EVENTBRITE_URL are added the same way once you have them (wayfinder ticket 03)."
note "Public values are baked in at build time: redeploy after changing one."
pause

# Stage 4
stage "Resend: sending domain and API key"
say "Enquiry emails are sent by a Sanity Function through Resend from the site's domain."
open_url "https://resend.com/domains"
step "Add domain omoyorubaofsocal.org, then create the DNS records it shows at your DNS host."
step "Wait for the domain to verify (the page refreshes its status)."
open_url "https://resend.com/api-keys"
step "Create an API key named 'sanity enquiry-notify' with Sending access only, copy it."
ask_secret RESEND_API_KEY "Paste the Resend API key:"
WEB_ENV_FILE="$ENV_FILE"; ENV_FILE="$FUNCTIONS_ENV_FILE"
write_env RESEND_API_KEY "$RESEND_API_KEY"
ENV_FILE="$WEB_ENV_FILE"
note "Stored in $FUNCTIONS_ENV_FILE for the Sanity Function (Phase 2). It is not an Astro or Vercel variable."
pause

# Stage 5
stage "PostHog: project and key"
say "Analytics load after first paint, only when the key is set. No autocapture, no recording."
open_url "https://us.posthog.com/"
step "Create a project named 'Omo Yorùbá site' (US cloud)."
step "Open Settings, then Project, and copy the Project API key."
ask PUBLIC_POSTHOG_KEY "Paste the PostHog project API key:"
write_env PUBLIC_POSTHOG_KEY "$PUBLIC_POSTHOG_KEY"
write_env PUBLIC_POSTHOG_HOST "https://us.i.posthog.com"
if (( VERCEL_READY )) && confirm "Push the PostHog values to Vercel now?"; then
  vercel_env PUBLIC_POSTHOG_KEY "$PUBLIC_POSTHOG_KEY"
  vercel_env PUBLIC_POSTHOG_HOST "https://us.i.posthog.com"
  note "Redeploy so the new key is built into the site."
fi
pause

# Stage 6
stage "Chromatic: project token for CI"
say "Chromatic snapshots every pull request's Storybook (Phase 1). CI needs the token as a GitHub secret."
open_url "https://www.chromatic.com/start"
step "Sign in with GitHub, choose 'Add project', pick this repository."
step "Copy the project token it shows (starts with chpt_)."
ask_secret CHROMATIC_PROJECT_TOKEN "Paste the Chromatic project token:"
set_secret CHROMATIC_PROJECT_TOKEN "$CHROMATIC_PROJECT_TOKEN"
pause

# Stage 7
stage "Sanity: publish webhook (after Phase 4)"
say "The webhook purges the site's cache on publish. It needs /api/revalidate deployed first (Phase 4)."
if confirm "Is /api/revalidate deployed to production yet?"; then
  open_url "https://www.sanity.io/manage"
  step "Open the project, then API, then Webhooks, then Create webhook."
  step "Name: purge site cache. URL: $SITE_URL_DEFAULT/api/revalidate. Dataset: production."
  step "Trigger on create, update and delete. HTTP method POST."
  step "Secret: the value of SANITY_WEBHOOK_SECRET in $ENV_FILE."
  step "Projection: {_type, \"slug\": slug.current}. Save."
  pause "Saved? Press Enter to finish."
else
  SKIPPED+=("Sanity webhook: re-run this wizard after Phase 4 and answer yes at stage 7")
  note "Skipping the webhook for now."
fi

finish
